In [67]:
import pandas as pd

In [68]:
df=pd.read_csv('laptopPrice.csv')

In [69]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [70]:
df.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [71]:
df.tail()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [72]:
df.head(10)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,49999,3 stars,0,0
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [74]:
df.describe()

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [75]:
df.dtypes

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [76]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
818    False
819    False
820    False
821    False
822    False
Length: 823, dtype: bool

In [77]:
df.duplicated().sum()

np.int64(21)

In [78]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [79]:
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [80]:
df.drop_duplicates(inplace=True)

In [81]:
df.duplicated().sum()

np.int64(0)

In [82]:
df.dropna()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [83]:
df['brand']

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 802, dtype: object

In [84]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [85]:
df['brand'].nunique()

8

In [86]:
df['brand'].value_counts()

brand
ASUS      243
DELL      149
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      23
Avita       6
Name: count, dtype: int64

In [87]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [88]:
#brand="HP"
#processor_brand="Intel"
#processor_name="Core i5"
#ram_gb="8 GB"
#ssd="512 GB"
#Price<=70000

In [89]:
hp_df=df[df['brand']=='HP']

In [90]:
intel_hp_df=hp_df[hp_df['processor_brand']=="Intel"]

In [91]:
i5_intel_hp_df=intel_hp_df[intel_hp_df['processor_name']=="Core i5"]

In [92]:
ram8GB_i5_intel_hp_df=i5_intel_hp_df[i5_intel_hp_df['ram_gb']=="8 GB"]

In [93]:
ssd512_ram8GB_i5_intel_hp_df=ram8GB_i5_intel_hp_df[ram8GB_i5_intel_hp_df["ssd"]=="512 GB"]

In [94]:
ssd512_ram8GB_i5_intel_hp_df[ssd512_ram8GB_i5_intel_hp_df['Price']<=70000]

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
215,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,54990,4 stars,116,15
216,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,53990,4 stars,206,17
240,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,55999,4 stars,5,1
243,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,58340,4 stars,69,6
259,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,0 GB,ThinNlight,1 year,No,Yes,59999,4 stars,4,1
262,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,63990,4 stars,17,1
266,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,63990,4 stars,3,0
287,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,57990,4 stars,1541,123
326,HP,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,55990,4 stars,30,4
338,HP,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,61000,4 stars,1124,100

In [95]:
df.dtypes

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [96]:
df.drop(['rating','Number of Ratings','Number of Reviews','weight'],axis=1,inplace=True)

In [97]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,msoffice,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No warranty,No,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No warranty,No,No,57490

In [98]:
df.dtypes

brand              object
processor_brand    object
processor_name     object
processor_gnrtn    object
ram_gb             object
ram_type           object
ssd                object
hdd                object
os                 object
os_bit             object
graphic_card_gb    object
warranty           object
Touchscreen        object
msoffice           object
Price               int64
dtype: object

In [99]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [100]:
brand_dict={'ASUS':1, 'Lenovo':2, 'acer':3, 'Avita':4, 'HP':5, 'DELL':6, 'MSI':7, 'APPLE':8}

In [101]:
brand_dict

{'ASUS': 1,
 'Lenovo': 2,
 'acer': 3,
 'Avita': 4,
 'HP': 5,
 'DELL': 6,
 'MSI': 7,
 'APPLE': 8}

In [102]:
# df['brand']=df['brand'].map(brand_dict)

In [103]:
df.dtypes

brand              object
processor_brand    object
processor_name     object
processor_gnrtn    object
ram_gb             object
ram_type           object
ssd                object
hdd                object
os                 object
os_bit             object
graphic_card_gb    object
warranty           object
Touchscreen        object
msoffice           object
Price               int64
dtype: object

In [104]:
df['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [105]:
df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [106]:
processor_brand_dict={'Intel':1, 'AMD':2, 'M1':3}
processor_brand_dict

{'Intel': 1, 'AMD': 2, 'M1': 3}

In [107]:
# df['processor_brand']=df['processor_brand'].map(processor_brand_dict)

In [108]:
df.dtypes

brand              object
processor_brand    object
processor_name     object
processor_gnrtn    object
ram_gb             object
ram_type           object
ssd                object
hdd                object
os                 object
os_bit             object
graphic_card_gb    object
warranty           object
Touchscreen        object
msoffice           object
Price               int64
dtype: object

In [109]:
df['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [110]:
df['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [111]:
processor_name_dict={'Core i3':1, 'Core i5':2, 'Celeron Dual':3, 'Ryzen 5':4, 'Core i7':5,
       'Core i9':6, 'M1':7, 'Pentium Quad':8, 'Ryzen 3':9, 'Ryzen 7':10, 'Ryzen 9':11}

In [112]:
processor_name_dict

{'Core i3': 1,
 'Core i5': 2,
 'Celeron Dual': 3,
 'Ryzen 5': 4,
 'Core i7': 5,
 'Core i9': 6,
 'M1': 7,
 'Pentium Quad': 8,
 'Ryzen 3': 9,
 'Ryzen 7': 10,
 'Ryzen 9': 11}

In [113]:
# df['processor_name']=df['processor_name'].map(processor_name_dict)

In [114]:
df.dtypes

brand              object
processor_brand    object
processor_name     object
processor_gnrtn    object
ram_gb             object
ram_type           object
ssd                object
hdd                object
os                 object
os_bit             object
graphic_card_gb    object
warranty           object
Touchscreen        object
msoffice           object
Price               int64
dtype: object

In [115]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [116]:
processor_gnrtn_dict={'10th':1, 'Not Available':2, '11th':3, '7th':4, '8th':5, '9th':6, '4th':7,
       '12th':8}
processor_gnrtn_dict

{'10th': 1,
 'Not Available': 2,
 '11th': 3,
 '7th': 4,
 '8th': 5,
 '9th': 6,
 '4th': 7,
 '12th': 8}

In [117]:
# df['processor_gnrtn']=df['processor_gnrtn'].map(processor_gnrtn_dict)

In [118]:
df.dtypes

brand              object
processor_brand    object
processor_name     object
processor_gnrtn    object
ram_gb             object
ram_type           object
ssd                object
hdd                object
os                 object
os_bit             object
graphic_card_gb    object
warranty           object
Touchscreen        object
msoffice           object
Price               int64
dtype: object

In [119]:
cat_columns = df.select_dtypes(include='object').columns

for col in cat_columns:
    unique_vals = df[col].unique()
    mapping_dict = {}
    i=1
    for val in unique_vals:
        mapping_dict[val]=i
        i+=1
    df[col] = df[col].map(mapping_dict)

In [120]:
df['ram_gb'].unique()

array([1, 2, 3, 4])

In [121]:
df.dtypes

brand              int64
processor_brand    int64
processor_name     int64
processor_gnrtn    int64
ram_gb             int64
ram_type           int64
ssd                int64
hdd                int64
os                 int64
os_bit             int64
graphic_card_gb    int64
warranty           int64
Touchscreen        int64
msoffice           int64
Price              int64
dtype: object

In [122]:
df.to_csv("clean_laptop_data.csv")

In [123]:
x=df.drop('Price',axis=1)
y=df[['Price']]

In [124]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,msoffice
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,2,1,1,1,1,1,1,1,1,1,1,1,1,1
2,2,1,1,1,1,1,1,1,1,1,1,1,1,1
3,1,1,2,1,2,1,2,2,1,2,2,1,1,1
4,1,1,3,2,1,1,1,3,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,1,1,5,2,1,1,1,2,1,1
819,1,2,11,2,1,1,5,2,1,1,1,2,1,1
820,1,2,11,2,1,1,5,2,1,1,3,2,1,1
821,1,2,11,2,1,1,5,2,1,1,3,2,1,1
822,2,2,4,1,2,1,2,2,2,1,1,1,1,1

In [125]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [126]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, random_state=42, test_size=0.2)

In [127]:
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,msoffice
442,1,1,2,3,2,1,3,1,1,2,1,2,1,2
598,1,1,5,1,3,3,1,3,2,2,4,1,1,1
452,1,1,2,3,2,1,3,1,1,1,2,2,1,2
696,6,2,4,2,2,1,2,2,1,1,1,2,1,2
339,1,1,2,3,2,3,2,2,1,1,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2,1,1,1,1,1,3,2,1,2,1,1,1,1
108,6,1,1,3,2,1,2,2,1,1,1,2,2,1
275,2,1,2,1,2,1,2,2,1,1,2,2,1,2
445,1,1,2,3,2,1,3,1,1,1,1,2,1,1
104,1,1,1,3,2,1,2,2,1,1,1,2,1,2

In [128]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,msoffice
196,3,1,2,2,2,4,1,3,1,2,3,1,1,1
299,1,1,2,3,2,3,2,2,1,2,1,2,1,2
171,6,1,1,1,2,1,3,1,1,1,1,2,1,2
537,5,1,5,1,3,1,5,2,1,1,4,2,1,2
551,7,1,5,3,3,1,5,2,1,1,5,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,1,1,2,3,2,3,2,2,1,1,1,2,2,1
361,5,1,2,1,2,1,2,2,1,1,1,2,2,1
446,6,1,2,3,2,1,3,1,1,1,1,2,1,1
767,2,2,10,2,1,1,2,2,1,1,3,2,1,1
529,2,1,5,3,3,1,2,2,1,2,1,1,1,1

In [129]:
y_train

      Price
442   50990
598  146490
452   60190
696   59490
339   99990
..      ...
73    41990
108   60790
275   57500
445   52990
104   44990

[641 rows x 1 columns]

In [130]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [131]:
x_test.shape, y_test.shape, x_train.shape, y_train.shape

((161, 14), (161, 1), (641, 14), (641, 1))

In [132]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
rfr =RandomForestRegressor()
rfr.fit(x_train, y_train)

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [133]:
rfr.score(x_test, y_test)

0.7196565292311758

In [134]:
rfr.score(x_train, y_train)

0.9488719762696707

In [135]:
rfr.predict(x_test)

array([ 92265.27285714,  73568.15142857,  42441.53333333, 138667.1       ,
       173405.415     , 162339.88      , 114115.30952381,  77939.8       ,
        59565.19664139, 125911.55333333,  37045.67      ,  42785.47      ,
        61474.86      , 127375.01392857,  67977.36      , 110993.07952381,
        71607.57333333,  42046.27333333,  61215.87059524, 141046.06383333,
        42092.16      ,  39407.18      ,  67887.81666667,  39597.88333333,
        40488.13866667,  41062.07333333,  65644.6       , 193561.68      ,
        65185.40694048,  39366.64      ,  56770.422     ,  59445.65382351,
        46486.65916667,  53804.1650641 ,  64703.53216667,  37109.82      ,
       204116.0952381 ,  70770.27      ,  56861.08      ,  68323.42357143,
        39545.2       ,  66368.91666667,  53008.63427778,  39338.35142857,
       110820.30952381,  59400.76770857, 121075.35833333,  70322.404     ,
        84093.52      , 105572.54333333, 181384.47      , 156629.10333333,
       105691.68619048,  71509.57      ,  74223.18      , 111651.96833333,
        83307.66      ,  48021.47809524,  92156.06      , 137405.39      ,
        70132.215     ,  36895.70857143,  38611.23809524,  64933.4       ,
        62950.26666667,  72162.88      , 137971.933     ,  40534.27      ,
        39814.46333333,  38967.43166667,  96573.08      , 143981.02333333,
       119620.31285714, 127375.01392857,  40820.48      ,  41444.75      ,
       154888.08333333,  86466.47      ,  59565.19664139,  57317.54369048,
        52793.52      ,  60391.51      ,  70282.17      ,  37045.67      ,
        42236.28      ,  56146.83333333,  91363.51583333,  94072.85666667,
        64885.52331459, 154532.99206349,  65649.09      ,  58041.95000702,
       100960.37571429, 105621.49858333,  43382.38333333, 100083.009     ,
       168862.68833333,  61474.86      ,  36845.74333333,  58653.92541667,
        47423.65      ,  39493.06033333,  84070.96166667,  52691.96333333,
        41760.66666667,  70132.215     ,  45410.88      , 110993.07952381,
        41120.46333333,  93933.1275    ,  74730.83496429,  80603.14      ,
        58315.84659524,  74223.18      ,  60483.28166667,  58738.75079365,
        36531.73809524,  68204.6       ,  58580.18      ,  43847.77      ,
       121786.3075    ,  59112.67333333,  59565.19664139,  64054.15      ,
        56565.20508333,  71043.22      ,  39814.46333333,  50603.12542857,
       161123.42333333,  54895.31      ,  66823.3922619 ,  73494.27316667,
        85250.22      , 188677.66      ,  38799.35      ,  68960.075     ,
       133907.26666667, 107126.99      ,  72418.71      ,  63446.1       ,
       180092.24      ,  41154.87      ,  64797.55      , 108118.295     ,
        65396.62107143, 122438.79066667,  70335.27166667,  63016.97      ,
        56697.16      ,  89696.3905    ,  66823.3922619 , 127375.01392857,
        55551.42571429,  38069.8635    ,  38322.        , 138357.71      ,
       100960.37571429, 109911.68258333,  58496.735     ,  83709.36      ,
        94025.93      ])

In [136]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [137]:
import joblib
joblib.dump(rfr, 'model.joblib')

['model.joblib']

In [138]:
model= joblib.load('model.joblib')