In [105]:
import tensorflow as tf
import numpy as np

In [106]:
import pandas as pd

In [107]:
df = pd.read_csv('clean_bike_data.csv')

In [108]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [109]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
7319   25000.0     48587.0      1  8.0  150.0      6
7320   35000.0     60000.0      1  9.0  220.0      7
7321  450000.0      3430.0      1  4.0  750.0     15
7322  139000.0     21300.0      1  4.0  400.0      7
7323   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [110]:
x=df.drop('price' ,axis = 1)
y=df['price']

In [111]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7319     48587.0      1  8.0  150.0      6
7320     60000.0      1  9.0  220.0      7
7321      3430.0      1  4.0  750.0     15
7322     21300.0      1  4.0  400.0      7
7323      7127.0      1  5.0  220.0      7

[7324 rows x 5 columns]

In [112]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
7319     25000.0
7320     35000.0
7321    450000.0
7322    139000.0
7323     80000.0
Name: price, Length: 7324, dtype: float64

In [113]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=42)

In [114]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [115]:
input_shape = x_train.shape[1]
input_shape

5

In [116]:
model=Sequential()
model.add(Dense(units=128, activation='relu', input_dim=(input_shape)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))

model.add(Dense(units=1, activation='linear'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy','mae', 'mse'])

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [117]:
model.fit(x_train,y_train, epochs=10, batch_size=32)

Epoch 1/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0000e+00 - loss: 21892433920.0000 - mae: 78137.0156 - mse: 21892433920.0000
Epoch 2/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 19704811520.0000 - mae: 72249.3594 - mse: 19704811520.0000
Epoch 3/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 19071088640.0000 - mae: 68441.6797 - mse: 19071088640.0000
Epoch 4/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 10416273408.0000 - mae: 42157.7148 - mse: 10416273408.0000
Epoch 5/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 4408392704.0000 - mae: 31970.8574 - mse: 4408392704.0000
Epoch 6/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 4481280000.0000 - mae: 30385.9922 - mse: 4481280000.0000
Epoch 7/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 4184645888.0000 - mae: 31322.4727 - mse: 4184645888.0000
Epoch 8/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 4826683904.0000 - mae: 30879.8730 - mse: 4826683904.0000
Epoch 9/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 3768356864.0000 - mae: 28623.6016 - mse: 3768356864.0000
Epoch 10/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 3741647872.0000 - mae: 29450.0605 - mse: 3741647872.0000

In [118]:
pred=model.predict(x_test)

46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [119]:
pred

array([[ 97502.61 ],
       [317748.38 ],
       [ 63225.652],
       ...,
       [ 30706.584],
       [228079.61 ],
       [ 73736.164]], dtype=float32)

In [120]:
y_test

3795     88400.0
1562    102850.0
4480     67000.0
3718     30000.0
5887     20000.0
          ...
4417    395000.0
527     140000.0
3309     54500.0
5077    114000.0
565      36000.0
Name: price, Length: 1465, dtype: float64

In [121]:
pred=np.ravel(pred)

In [122]:
pred

array([ 97502.61 , 317748.38 ,  63225.652, ...,  30706.584, 228079.61 ,
        73736.164], dtype=float32)

In [123]:
pd.DataFrame({'actual':y_test, 'prediction':(pred>=0.5).astype(int)})

        actual  prediction
3795   88400.0           1
1562  102850.0           1
4480   67000.0           1
3718   30000.0           1
5887   20000.0           1
...        ...         ...
4417  395000.0           1
527   140000.0           1
3309   54500.0           1
5077  114000.0           1
565    36000.0           1

[1465 rows x 2 columns]

In [124]:
# pd.concat([y_test, pred], axis=1)